### ISSUE TITLE
Use links also on import from bibtex

### ISSUE THREAD

**Issue by laclaro** [ZotPlus/zotero-link-local-files#5] opened 2018-01-18 15:34 UTC
Hi,

I try to create a portable zotero installation on a network drive. It works, but I don't want to import all the files but to link them.

There is plenty of discussions going on
https://forums.zotero.org/discussion/2358/home-dir-relative-storage-of-linked-files/p4
https://forums.zotero.org/discussion/comment/159416/
https://github.com/zotero/zotero/issues/329

Can I achieve this via some kind of js-snippet?

Yours does not get triggered unfortunately.

Best,

Henning

**Comment by retorquere** [comment] 2018-01-19 07:13
This extension has not yet been ported to Zotero 5. It may be the case that Zotfile does what you need.

**Comment by laclaro** [comment] 2018-01-22 10:09
I already tried and Zotfile is not the solution. Zotfile only watches certain directories to import files automatically to Zotero or syncs with some other directory (e.g. on a tablet). There are no linking options.

Yes, your plugin only works with Zotero 4. I don't care to use version 4 (actually I already installed it to test your plugin). Could you add a snippet to your code to apply the "link-only" also for the import (from bibtex) functionality? I tried, but I don't know anything about this JS-Stuff.

Best,

Henning

**Comment by retorquere** [comment] 2018-01-22 10:28
I have plans to resurrect this plugin but they're not short-term plans. Have you looked at https://www.zotero.org/support/sync#alternative_syncing_solutions ?

**Comment by peeter-t2** [comment] 2018-08-12 14:04
A combination of this + Zotfile on Zotero 4 worked for me to import from bibtex. It seemed to work precariously in a few select settings. A fair warning, Zotero 4 will stop being able to sync at August 18, 2018 so using Zotero 4 as a workaround will not work soon.

**Comment by retorquere** [comment] 2018-08-12 20:56
This is technically a duplicate of #4; there's nothing special about bibtex imports, if #4 works, it will work for all imports.

**Closed as completed by retorquere** 2018-08-12 20:56 UTC
Labels: duplicate
